version: "3.9"

services:
  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    ports:
      - "3310:3310"
    environment:
      - CLAMD_LOG_STDERR=true
    volumes:
      - ./clamav-data:/var/lib/clamav
    restart:
      unless-stopped
    networks:
      - clamav-network

networks:
  clamav-network:
    driver: bridge